// Automatisch generierter Code. Nicht bearbeiten.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "-°":return img`
................................
................................
................................
................................
.............ffffffff...........
...........ffccccccccff.........
..........fccbbffffbbccf........
.........fcbbff7777ffbbcf.......
........fcbbf77777777fbbcf......
........fcbf7ff7777ff7fbcf......
........fcbf7f1f77f1f7fbcf......
.......fcbbbf7ff77ff7fbbbcf.....
.......fcffbf77777777fbffcf.....
.......ff77fbf773377fbf77ff.....
.....ffffffffffffffffffffffff...
....f6688668866aaaa6688668866f..
...ffffffffffffffffffffffffffff.
..ff9f9ffefeff9f9ffefeff9f9ffeff
..fff9ffffeffff9ffffeffff9ffffff
...f9f9ffefeff9f9ffefeff9f9ffef.
....ffffffffffffffffffffffffff..
.....fcccccfbfaaaaaafbfcccccf...
......fccccfbbfaaaafbbfccccf....
.......ffcccfbfaaaafbfcccff.....
.........ffcfbbfaafbbfcff.......
...........ffbbfaafbbff.........
.............ffffffff...........
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Automatisch generierter Code. Nicht bearbeiten.
